#!/bin/bash
# if $newrev is 0000...0000, it's a commit to delete a ref.
z40=0000000000000000000000000000000000000000

while read local_ref local_sha remote_ref remote_sha
do
    if [ "$local_sha" = $z40 ]
    then
        # Handle delete
        "Delete found skipping reviewboard post"
    else
        if [ "$remote_sha" = $z40 ]
        then
            # Handle new branch
            echo "New branch found skipping reviewboard post"
        else
            # Update to existing branch, examine new commits
            range="$remote_sha..$local_sha"
            echo "Calling post-to-reviewboard with powershell, git range:"
            echo $range
            exec powershell.exe -NoProfile -ExecutionPolicy Bypass -File ".\git-hooks\post-to-reviewboard.ps1" -range $range
            echo "End call to post-to-reviewboard"
        fi
    fi
done
exit 0
