---
title: "`phenoptr` in ten hundred words"
author: "Kent Johnson"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    df_print: kable
    toc: true
---

# phenoptr helps  with inForm numbers and pictures

`phenoptr` makes it easier to read and use number tables and 
pictures made by PerkinElmer's inForm<sup>&reg;</sup> computer worker.
`phenoptr` is part of the PerkinElmer Phenoptics&trade; family of Quantitative
Pathology Research Solutions. For more facts visit the Phenoptics™ 
Phenoptics&trade;
[home place](http://www.perkinelmer.com/cancer-immunology/index.html).

## How to get it

Get phenoptr from GitHub:

```
# install.packages("devtools")
devtools::install_github("PerkinElmer/phenoptr", build_vignettes=TRUE)
```

## How to use it

`phenoptr` works well with many parts of the
[tidyverse](http://tidyverse.org/).

- [readr](http://readr.tidyverse.org/) is used to read number tables.
- [tibbles](http://tibble.tidyverse.org/) (also known as `data_frame`)
  are used to hold number tables.
- [dplyr](http://dplyr.tidyverse.org/), [purrr](http://purrr.tidyverse.org/)
  and this funny thing ([`%>%`](http://magrittr.tidyverse.org/))
  are used a lot to help show you how to do things.

If you'd like to learn how to use the tidyverse, a good place to start is Garrett Grolemund and Hadley Wickham's free book 
[R for data science](http://r4ds.had.co.nz/).

### What this can do

#### Read and clean up inForm number tables and pictures

[list_cell_seg_files](https://perkinelmer.github.io/phenoptr/reference/list_cell_seg_files.html)
finds all inForm cell number tables from one place on your computer.

[read_cell_seg_data](https://perkinelmer.github.io/phenoptr/reference/read_cell_seg_data.html)
reads inForm cell number tables and makes them easier to use in R.

[read_components](https://perkinelmer.github.io/phenoptr/reference/read_components.html) 
and [read_maps](https://perkinelmer.github.io/phenoptr/reference/read_maps.html) 
read inForm pictures.

#### Find and draw position relationships between cells

[find_nearest_distance](https://perkinelmer.github.io/phenoptr/reference/find_nearest_distance.html)
finds how far each cell is to the nearest cell of each kind.

[count_within](https://perkinelmer.github.io/phenoptr/reference/count_within.html)
finds the number of cells that are not too far from cells of another kind.
[count_within_batch](https://perkinelmer.github.io/phenoptr/reference/count_within_batch.html) 
does this for lots of kinds of cells from lots of pictures.

[spatial_distribution_report](https://perkinelmer.github.io/phenoptr/reference/spatial_distribution_report.html) 
makes a paper showing nearest friend relationships between cells of two kinds.

[count_touching_cells](https://perkinelmer.github.io/phenoptr/reference/count_touching_cells.html)
looks at the form of cells to find, number, and make pictures of touching cells in paired groups.

#### Helpers

[distance_matrix](https://perkinelmer.github.io/phenoptr/reference/distance_matrix.html)
makes number tables showing how far cells are from each other.


[subset_distance_matrix](https://perkinelmer.github.io/phenoptr/reference/subset_distance_matrix.html)
helps when you just want to use some of the cells.

[select_rows](https://perkinelmer.github.io/phenoptr/reference/select_rows.html)
picks cells in cell number tables that have the kind and numbers you are interested in.

### Full documentation

For more words see the 
[Articles](https://perkinelmer.github.io/phenoptr/articles/index.html) and 
[Reference](https://perkinelmer.github.io/phenoptr/reference/index.html)
parts of the  words.

For more words showing how to use it and more number tables and pictures 
to try out, go to the 
[phenoptrExamples](https://perkinelmer.github.io/phenoptrExamples) place.

## What is this?

This place is just for fun. 
It was made using only the ten hundred most used words (and some names). 
It was made with help 
from [upgoer5](http://splasho.com/upgoer5/). 
The idea is from [XKCD](http://xkcd.com/1133/).
